### ISSUE TITLE
(Bug klo waktu pengerjaan habis)Pastikan student tidak bisa membuka materi melalui tab baru ketika sedang mengerjakan latihan soal

### ISSUE THREAD

**Issue by Cibobhap** [ARusDian/ABC-CAT#11]
Pastikan student tidak bisa membuka materi melalui tab baru di browser ketika sedang mengerjakan latihan soal

kata pak fajri, pakai cache, buat redirect(?))

**Comment by Uskrai** [comment]
udah bisa

**Comment by AngelaCathe** [comment]
user sudah gak bisa buka materi di tab baru klo lagi ngerjain tes 👍

another bug @Uskrai :

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/df4c02e0-2ade-4bcc-a6ce-e2eb9e353dd2)

**ISSUE BARU**
sekarang issuenya, klo waktu pengerjaan selesai, tesnya gak otomatis tertutup lagi kayak sebelumnya, jadi kalau mau nutup halaman ujiannya, user harus pencet button "selesai ujian" atau ngereload halamannya, trus user juga masih bisa milih2 jawaban walaupun waktunya udh habis(untungnya, jawaban yg dipilih setelah waktunya habis gak tersimpan di database) 

edit:
aku buka consolenya, ada error:


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/ba66bef0-19e3-4fd2-b024-2acd928ef712)

**Comment by Uskrai** [comment]
udah

**Comment by AngelaCathe** [comment]
@Uskrai 
di laptopku, dia memang langsung auto reload, tapi dia malah kembali kek gini: 


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/39fc9594-68ca-45b5-b937-b43b5355a633)

selain itu, tombol nextnya juga nge bug, bisa diklik, trus nomor soalnya nambah trus melebih jumlah soalnya:


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/7cfe7dd8-d23f-4321-876b-ae48647d9ca8)

**Comment by Uskrai** [comment]
udah

**Comment by AngelaCathe** [comment]
di laptopku masih kak @Uskrai

**Comment by Uskrai** [comment]
kirim ss full

**Comment by AngelaCathe** [comment]
bntr aku makan dulu, baru aku coba jalanin latihan soalnya lagi

**Comment by AngelaCathe** [comment]
habis aku cek, yang bermasalah tiap kali waktunya habis cuma soal kecermatan aja, untuk soal2 lain aman, langsung tertutup halamannya klo waktu pengerjaannya udah habis.

ss yg kecermatan:
![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/2f34b23c-9a86-48aa-b838-0343f5a5a273)

jadi klo di kecermatan, waktunya tiba2 ketambah lagi 59 detik

**Comment by Uskrai** [comment]
udah

**Comment by AngelaCathe** [comment]
![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/278c9962-9112-463b-a78f-b25b547336c4)

@Uskrai

**Comment by Uskrai** [comment]
Ini udah kan?

**Comment by AngelaCathe** [comment]
> Ini udah kan? @Uskrai 

gk tau kenapa di laptopku masih error trus eh yg ini, masih kek yg tadi, gak mau auto nutup dia klo waktunya habis:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/278c9962-9112-463b-a78f-b25b547336c4)

error di consolenya sama. Ini aku mintol amel coba kerjain dari PCnya dia. klo di laptop kak fatur bisa kah?

EDIT: di PC amel juga errornya sama

**Comment by AngelaCathe** [comment]
@ARusDian klo gak, bisa coba tes di laptopmu kah rus? coba kerjain yang kecermatannya, sampe waktunya habis. tolong liatkan, halaman tesnya langsung ketutup atau nggak pas waktunya habis, atau error kek gambar di atas.

**Comment by AngelaCathe** [comment]
bugnya kembali untuk semua tipe soal keknya:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/4e4dbaab-0dae-46cf-862c-3780f5c41cf0)

**Comment by Uskrai** [comment]
cek lagi

**Comment by AngelaCathe** [comment]
okok sek

**Comment by AngelaCathe** [comment]
di soal2 lain yang umum sudah aman 👍 ,

masih masalah yg sama untuk soal kecermatan

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/074383d8-0bd3-4cd0-beb2-0c9b357f79e6)

**Comment by Uskrai** [comment]
coba lagi

**Comment by AngelaCathe** [comment]
masih kak, ini aku ss kan error yg di laravelnya juga:


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/ab18a349-7c9f-4865-8e49-8487deb3c779)

**Comment by Uskrai** [comment]
coba lagi

**Comment by AngelaCathe** [comment]
AKHIRNYA YAALLAH BAPA

UDAH BISAAA 🎊

 GG @Uskrai
