### ISSUE TITLE
Terkait aspek latihan soal

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#15]
aspek soal ditentukan melalui penamaan bank soal. Nantinya, ketika admin menambahkan latihan soal baru, admin bisa menggabungkan dan mengacak soal2 dari bank soal berdasarkan aspeknya(a.k.a nama bank soalnya).

semua aspek soal yang digunakan dalam satu latihan soal akan digenerate dan diacak secara merata.

**Comment by Uskrai** [comment]
> semua aspek soal yang digunakan dalam satu latihan soal akan digenerate dan diacak secara merata

ada banyak soal yg gk merata di contoh yang dikasih. ini maunya di kasih opsi untuk aspek per soal atau gimana?

contoh: 
![image](https://github.com/ARusDian/ABC-CAT/assets/30656271/e353d15f-5e37-46a4-8620-b3f11923d78c)

**Comment by AngelaCathe** [comment]
> ada banyak soal yg gk merata di contoh yang dikasih. ini maunya di kasih opsi untuk aspek per soal atau gimana? - @Uskrai 

o iya ya gak sama rata jumlahnya, kayaknya karna total soalnya 100, tapi aspeknya 8, jadinya gk bener2 bisa dibagi rata, kira2 bisa kah kak kalau misalnya:

(total jumlah soal) mod (jumlah aspeknya) ≠ 0

*kalau mau dibagi rata, bakal ada sisa soal

gimana kalau ntar soal yang tersisa(sisa dari modulusnya), aspeknya di random? biar ntar aspek yang soalnya lebih itu diacak aja.
soalnya dari yang kutangkap, keknya tiap latihan soalnya pake aspek semua

**Comment by Uskrai** [comment]
udah bisa di test

**Comment by AngelaCathe** [comment]
> udah bisa di test - @Uskrai 

nice, laporan hasilnya udah keluar:
![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/6bbb261c-4082-4b59-92a9-383cb6ca8342)

tinggal isinya aja :O

**Comment by AngelaCathe** [comment]
oke, yang bug dari sisi admin juga udah aman 👍 @Uskrai nice2

berarti tinggal isi laporannya aja kakk

**Comment by Uskrai** [comment]
>berarti tinggal isi laporannya aja kakk

isi laporan apa?

**Comment by AngelaCathe** [comment]
> isi laporan apa? - @Uskrai 

maksudnya data hasil pengerjaan tesnya kak, kek untuk aspek a, waktunya berapa, jumlah benar salahnya berapa, yg kek di bawah:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/bca90982-a016-451f-8407-e97c4da0f10f)

klo yg aku ss sebelumnya kan masih kosongan

**Comment by AngelaCathe** [comment]
bug @Uskrai :
pas admin mau liat hasil ujian dari salah satu user(ngaksesnya dari view data user), kek gambar di bawah:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/e15ed27c-8fd0-4c53-be90-4b84246c465c)

halamannya masih kosong:


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/7239d49c-4f03-46e3-8036-9331ea8cd028)

**Comment by Uskrai** [comment]
> maksudnya data hasil pengerjaan tesnya kak, kek untuk aspek a, waktunya berapa, jumlah benar salahnya berapa, yg kek di bawah:

 udah

> halamannya masih kosong:

kalo halaman kosong kyk gini yang di ss consolenya

**Comment by AngelaCathe** [comment]
> udah - @Uskrai 

okok klo di admin udah aman, aspek sama nilai2nya udah muncul semua 👍 (kalo yg waktu pengerjaan ntar di issue #12 )
klo ngeliat hasil dari akun student masih belum

> kalo halaman kosong kyk gini yang di ss consolenya

maap bang 🗿 🙏

**Comment by Uskrai** [comment]
> hasil dari akun student masih belum

Belum apa?

**Comment by AngelaCathe** [comment]
> Belum apa? - @Uskrai 

data hasil tesnya belum muncul(masih kosong semua):

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/7c7fc176-7783-4c46-a957-1eccf5b377bf)

consolenya kek gini:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/8a1b501e-2754-4eef-82ec-b032611e53ac)

**Comment by Uskrai** [comment]
udah

**Comment by AngelaCathe** [comment]
niceee udah bisa semuaa, waktunya juga udah kerekam 👍
issuenya kututup ya @Uskrai aman dahh
