### ISSUE TITLE
laporan hasil pengerjaan soal

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#17]
Laporan Hasil Tes dibagi2 berdasarkan aspek soal

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/9282a265-88fb-4590-9fa1-0f8b4a86b1ab)

![Image](https://github.com/ARusDian/ABC-CAT/assets/87649208/0e84abc9-df65-4d42-b295-cb8a0f251118)

**Comment by ARusDian** [comment]
Btw disini bisa upload foto

**Comment by AngelaCathe** [comment]
hooh udah, aman2

**Comment by ARusDian** [comment]
No Tes Itu mau diambil di ID pengerjaan ujian atau ID latihan soalnya?

**Comment by Uskrai** [comment]
> No Tes Itu mau diambil di ID pengerjaan ujian atau ID latihan soalnya?

ambil id dari tabel exam

**Comment by ARusDian** [comment]
Export Pagenya udh ada tinggal diganti valuenya ya @Uskrai

**Comment by Uskrai** [comment]
> Export Pagenya udh ada tinggal diganti valuenya ya @Uskrai

gimana cara bukanya rusdin

**Comment by ARusDian** [comment]
di user.exam.result

Masuknya lewat data user

**Comment by Uskrai** [comment]
udh bisa di test

**Comment by Uskrai** [comment]
@AngelaCathe @Cibobhap udah kalian test kah

**Comment by AngelaCathe** [comment]
@Uskrai udah kak, aku ada buat issue baru lagi, ada kujelasin di situ. Kebetulan yang terbuka malah hasil ujian dari soal lain yang tipenya kecermatan, jadi gada aspeknya.

**Comment by AngelaCathe** [comment]
oh iya, untuk yang kecermatan, bisa kah rus kolom "aspek" diganti namanya jadi "Kolom"? @ARusDian 


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/9aa1cfd3-42b8-4c44-b5c2-4832822a04f1)


jadi ntar untuk tiap 50 soal, nama tiap barisnya jadi "kolom 1", "kolom 2", dst.

edit: kayak contoh yg dikasih orangnya:

![Image](https://github.com/ARusDian/ABC-CAT/assets/87649208/0e84abc9-df65-4d42-b295-cb8a0f251118)

**Comment by Uskrai** [comment]
> oh iya, untuk yang kecermatan, bisa kah rus kolom "aspek" diganti namanya jadi "Kolom"? @ARusDian

udah

**Comment by AngelaCathe** [comment]
btw, ada bug lagi 😅 @Uskrai @ARusDian 


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/9526ae86-0892-47ab-8290-9044786cdb05)

klo admin klik "SHOW", yang keluar malah laporan hasil tesnya(sama kayak kalau ngeklik tombol "Lihat Hasil"), bukan evaluasi yang kek biasanya, yang bisa lihat soalnya satu2 sama jawaban studentnya

edit: gak cuma di kategori kecermatan, kategori lain juga sama

**Comment by Uskrai** [comment]
>klo admin klik "SHOW", yang keluar malah laporan hasil tesnya(sama kayak kalau ngeklik tombol "Lihat Hasil"), bukan evaluasi yang kek biasanya, yang bisa lihat soalnya satu2 sama jawaban studentnya

udah

**Comment by AngelaCathe** [comment]
masih kak klo di laptopku, belum live kah? @Uskrai 

masih keluar laporan yg ini klo dari akun admin:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/1d164a8c-cef3-41ca-8e1c-c6f901884737)

kalau yang di student aman, setelah klik tombol "Evaluasi":

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/a85d4468-f99e-4c45-a34c-625c7ebffc39)

yang keluar beneran evaluasi/review nya, yg ini:


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/378ee1d7-f5b2-423e-ae07-d10f6986dd0a)

**Comment by Uskrai** [comment]
udah

**Comment by AngelaCathe** [comment]
@Uskrai okokk udah bisaa,

tapi waktu pengerjaan per aspek yang ada di laporan hasil tes ngilang lagi 💀 : 


![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/109850eb-4984-43a6-bd85-5c494b97e246)

**Comment by Uskrai** [comment]
jgan dicrop gambarnya biar gampang ceknya

**Comment by AngelaCathe** [comment]
![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/e7034dec-3b7b-4b46-9e88-70ddf7e80ee0)

**Comment by Uskrai** [comment]
klo udah selesai kerjain counternya udah kesimpan, jadi gk bisa berubah lagi. coba bikin baru lagi.

**Comment by AngelaCathe** [comment]
@Uskrai okok udah aman semua 👍 

aku tutup issuenya ya
