### ISSUE TITLE
Tambahkan Kategori untuk soal kecermatan

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#18]
![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/12f6d3b4-39ab-4661-80f6-6fdeb8e1ac3b)

Untuk soal kecermatan, terdapat kategori untuk tiap kolom, yaitu:
 "sangat baik," "baik," "cukup," "kurang," "sangat kurang," 
yang dikategorikan berdasarkan jumlah soal yang benar di tiap kolom yang dikerjakan oleh murid.

**Comment by ARusDian** [comment]
ini perlu dong ketentuan nilainya gmn kategorinya sama ini cuma di tampilannya aja kan?

**Comment by AngelaCathe** [comment]
> ini perlu dong ketentuan nilainya gmn kategorinya - @ARusDian 

brarti ntar kita mintakan pak fajri dulu ya, untuk dimintakan dari kliennya
edit: aku udh pc pak fajri, ntar kukabarin klo udh ada dikasih

> ini cuma di tampilannya aja kan? - @ARusDian 

kayaknya iya deh, buat laporan hasil tesnya aja

**Comment by AngelaCathe** [comment]
@ARusDian ini udh ada diimplemen kah rus dari yg dikirim pak fajri?

klo belum, aku copas di sini yo ketentuan nilainya:

**Kalau "kurang" poin dibawah 20**
**"Cukup" < 21**
**"Baik" >22**
**" sangat baik " >25**

**Comment by AngelaCathe** [comment]
okeoke udah ku cek, ketentuan kategorinya udah diimplemen ya, issuenya kututup @ARusDian
