### ISSUE TITLE
When admin import students through excel, the button should be disabled so the admin knows the import is still being processed

### ISSUE THREAD

**Issue by Cibobhap** [ARusDian/ABC-CAT#19]

**Comment by ARusDian** [comment]
Udah tinggal dicek

**Comment by AngelaCathe** [comment]
> Udah tinggal dicek - @ARusDian 

nice, buttonnya udh bisa. tapi user yg mau kuimport gk ketambah di daftar usernya rus

**Comment by ARusDian** [comment]
> user yg mau kuimport gk ketambah di daftar usernya rus

seriusan? sek

**Comment by AngelaCathe** [comment]
.

**Comment by ARusDian** [comment]
ini nunggu di live aja soalnya klo ditmptku prosesnya cpt jadi g keliatan ada loadingnya

**Comment by AngelaCathe** [comment]
> ini nunggu di live aja soalnya klo ditmptku prosesnya cpt jadi g keliatan ada loadingnya

okok

**Comment by Uskrai** [comment]
> ini nunggu di live aja soalnya klo ditmptku prosesnya cpt jadi g keliatan ada loadingnya

Pamer amat anjim ni orang

**Comment by AngelaCathe** [comment]
> ini nunggu di live aja soalnya klo ditmptku prosesnya cpt jadi g keliatan ada loadingnya @ARusDian 

sekarang di laptopku juga gada yang loadingnya rus, button "IMPORT STUDENT" nya tetep bisa diklik 💀 

btw, klo pake template import student yg barusan kamu taroh, aku dapat error kek gini:

https://flareapp.io/share/LPdgjgym

**Comment by AngelaCathe** [comment]
> Pamer amat anjim ni orang

makanya ckckck rusdin rusdin 💀 💀

**Comment by ARusDian** [comment]
yang import udh bisa tpi loading blman

**Comment by ARusDian** [comment]
ini udh bisa kn?

**Comment by AngelaCathe** [comment]
udah aman rus, ty ty issuenya kututup yo
