### ISSUE TITLE
NEW BUG!🐛 😢 Import Soal

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#21]
pas mau import soal, dan sudah mengisi sesuai template yang tersedia, ada error kek di bawah ini:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/2d2a917c-d9f0-476f-b861-0c4162d30e07)

error link: https://flareapp.io/share/dmkbdgD5

karena katanya "unknown column", jadi kolom "bobot" aku hilangin, trus ada dapat error kek gini:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/14c9035e-a5b5-4f96-8c44-ac0b677f2f02)

error link: https://flareapp.io/share/x7Kb6nZP

**Comment by ARusDian** [comment]
ke gw aja ini

**Comment by AngelaCathe** [comment]
yg ini udh live kah rus? @ARusDian

**Comment by ARusDian** [comment]
udah
