### ISSUE TITLE
terangin warna tombol nomor soal yang sedang dikerjakan

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#23]
Untuk soal yang sedang terbuka/sedang dilihat di view, contohnya kek di bawah ini(udah nyampe di no. 3): 

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/5fda3205-ed2d-4b4e-bd05-9fedf68d00c3)

bisakah warna butir yang lagi dilihat di view, warnanya diterangin lagi atau ganti warna? agak susah dibedakan sama soal2 lain yang sudah terjawab

**Comment by ARusDian** [comment]
![Image](https://github.com/ARusDian/ABC-CAT/assets/87649208/e87d6541-abd7-4f32-ac17-2759e28bb737)

udh ya ini
