### ISSUE TITLE
Another bug 🪲terkait hasil tes

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#24]
ketika user mengklik button "Lihat hasil" setelah mengerjakan ujian:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/a767ad5c-729e-4036-b128-8a61dc5e92fd)

timbul error kek gini:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/2c5b169a-dd27-4505-8a40-2a5c07e513d3)

Error Link: https://flareapp.io/share/17D4v8X7

**Comment by Uskrai** [comment]
Duplicate of #15 

udah

**Comment by Uskrai** [comment]
kalo masih bug di tempet yang sama taro di issue yang sama
