### ISSUE TITLE
bugs 🐞masih di hasil ujian(dari sisi admin)

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#25]
ketika admin mau cek salah satu riwayat pengerjaan soal yang letaknya di kategori bahasa inggris, kek gini:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/04d50cf2-0c7e-4e8b-aed6-df437d7fb568)

yang terbuka malah hasil tes ujian lain, yang dikerjakan user lain:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/29358b0c-42a1-430d-a432-6699becb6ece)

kemudian, karena hasil yang ditampilkan adalah hasil dari ujian dengan judul "Newbie 1", maka saat mengklik button "kembali":

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/ebb6b355-e65c-46f9-ad79-66b21ddf02d6)

tampilan admin diarahkan ke leaderboard ujian "Newbie 1":

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/15738c48-09d6-4364-83a7-7e5e9a194b33)

**Comment by Uskrai** [comment]
screenshot gk usah di crop biar jelas, kalo bisa debugbarnya juga ditampilin

**Comment by Uskrai** [comment]
Duplicate of #15
