### ISSUE TITLE
Mintol bersihkan DB paket belajar(kecuali paket Kedinasan sama Kepolisian)

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#26]
@Uskrai kak faturr, bisa tolong hapus paket2 belajar lain kah selain paket belajar Kedinasan sama Kepolisian? soalnya mau aku dokumentasi untuk buku panduan 😅

yg ini:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/a089eb83-85bd-45dc-a338-574ed8413fb3)

**Comment by Uskrai** [comment]
@ARusDian

**Comment by Uskrai** [comment]
udah

**Comment by AngelaCathe** [comment]
okokk thx yu
