### ISSUE TITLE
🪲bug saat import soal

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#28]
ketika admin import soal berbobot, terdapat error berikut:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/e3c371cd-f72a-4636-a31e-9b621abae435)

erorr link: https://flareapp.io/share/v5pnA8DP

**Comment by AngelaCathe** [comment]
@ARusDian btw rus, bisa kah untuk templatenya, mungkin yg contoh pengisiannya gak usah dibikin bold? biar orang gk bingung ntar ngisinya di mana. kek gini:



![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/00807444-6d9d-48c6-8277-365e238cd9eb)

**Comment by ARusDian** [comment]
> @ARusDian btw rus, bisa kah untuk templatenya, mungkin yg contoh pengisiannya gak usah dibikin bold? biar orang gk bingung ntar ngisinya di mana. kek gini:
> 
> 
> 
> ![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/00807444-6d9d-48c6-8277-365e238cd9eb)
> 
> 

Bisa tpi buat Issue baru aja :"

**Comment by AngelaCathe** [comment]
baiklah bang

**Comment by ARusDian** [comment]
ini udh kupush tpi ditempatku ndd error kek gini (cuma dilinux doang soalnya) jadi kurang tau work apa kaga

**Comment by Uskrai** [comment]
udah?

**Comment by AngelaCathe** [comment]
niceee udah aman rus, yg tunggal sama ganda bisa semua. 👍 

issue kututup ya
