### ISSUE TITLE
Fix template import soal(UI/UX)

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#29]
untuk template import soal, mungkin contoh pengisiannya gak usah dibikin bold, biar orang yg ngisiin gak bingung isinya di mana. 

jadinya kek gini:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/ad584d53-20ac-4d9e-b258-89748f052aa7)

**Comment by ARusDian** [comment]
dh

**Comment by ARusDian** [comment]
[Template Soal Pilihan Jawaban Tunggal (3).xlsx](https://github.com/ARusDian/ABC-CAT/files/12442280/Template.Soal.Pilihan.Jawaban.Tunggal.3.xlsx)


[Template Soal Pilihan Jawaban Ganda (2).xlsx](https://github.com/ARusDian/ABC-CAT/files/12442294/Template.Soal.Pilihan.Jawaban.Ganda.2.xlsx)



[users_template.xlsx](https://github.com/ARusDian/ABC-CAT/files/12442296/users_template.xlsx)

**Comment by Uskrai** [comment]
udah kan?

**Comment by AngelaCathe** [comment]
aman aman
