### ISSUE TITLE
Example Value Of Excel Import

### ISSUE THREAD

**Issue by ARusDian** [ARusDian/ABC-CAT#3]
Make input Examples for Excel Imports(as guidance for their admin)
Things to be added in the templates:
1. For user registration template, you forgot the "password" field
2. Make the templates look nicer if you can please, make it readable so it won't confuse their admins
-ngela

**Comment by ARusDian** [comment]
yang ini nunggu dari fatur fix datanya dl ya

**Comment by AngelaCathe** [comment]
okok
