### ISSUE TITLE
Baikin typo di Soal Kecermatan(UX)

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#30]
**untuk mengurangi kebingungan user:**

Dari sisi Admin, tolong ganti:

"Batas Waktu" ----> "Batas Waktu per Kolom"
"Jumlah Soal per Latihan" ----> "Jumlah Soal per Kolom"
 
di deskripsi latihan soal tipe Kecermatan, kek yg di bawah ini:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/8f849cd5-fdc7-4fb7-8b03-6a32b040e75b)

klo yang dari sisi Student,
tolong ganti:

"Jumlah Soal" ----> "Jumlah Soal per Kolom"
"Waktu Pengerjaan" ----> "Waktu Pengerjaan per Kolom"

di deskripsi latihan soal tipe kecermatan, kek di bawah ini:
![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/57d02cf2-1c46-431e-9670-e30f9deb11eb)

@ARusDian kira2 bisa kah rus, klo dirubah untuk yang tipe Kecermatan aja? Kalaupun bisa, kira2 sempat kah?
**Kalau misalnya gak bisa/gak sempat, reply yo**, biar gak usah dikerjakan dulu, karena gak terlalu urgent

**Comment by ARusDian** [comment]
smpt aja sek

**Comment by AngelaCathe** [comment]
okok

**Comment by AngelaCathe** [comment]
@ARusDian yg ini tinggal di live ya brarti

**Comment by ARusDian** [comment]
I
Iys

**Comment by Uskrai** [comment]
udah kan?

**Comment by AngelaCathe** [comment]
> udah kan?

udahh, aman2
