### ISSUE TITLE
Student cannot access Learning Material

### ISSUE THREAD

**Issue by Cibobhap** [ARusDian/ABC-CAT#31]
murid tidak bisa mengakses materi 

![Image](https://github.com/ARusDian/ABC-CAT/assets/104015817/dfbf72b5-d89b-4bad-bae4-905b73b6f682)

errornya:

![Image](https://github.com/ARusDian/ABC-CAT/assets/104015817/8b2c5c08-9e8b-4681-8b4f-6f21249dbb22)

error link: https://flareapp.io/share/A7Ekv1em

**Comment by ARusDian** [comment]
minta linkny

**Comment by ARusDian** [comment]
Udh ini ya tinggal di push

**Comment by Uskrai** [comment]
udah?

**Comment by AngelaCathe** [comment]
udah aman, ty ty
