### ISSUE TITLE
Tolong pisahkan paket2 latihan soal menjadi per kategori saja saat ingin memasukkan soal2 dari bank soal ke paket latihan yang sudah ada

### ISSUE THREAD

**Issue by Cibobhap** [ARusDian/ABC-CAT#33]
jika admin/guru mau masukin soal2 dari bank soal ke dalam paket latihan soal yang sdh perna di buat, 

bisa kah latihan soalnya jangan dicampur sama kategori lain ????. soalnya nanti paket2 latihannya bakal banyak dan jg kategorinya lebih banyak lagi, nanti gurunya bingung buat bedain lat soal mana yg berasal dari kategori yg dia ampu(takutnya ketimbun sm lat soal dari kategori lain).

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/b46dfb3c-4f1e-4681-ab8e-1bca666bc894)

**Comment by Uskrai** [comment]
ssnya jgn dicrop biar gampang ceknya

**Comment by Uskrai** [comment]
udah

**Comment by AngelaCathe** [comment]
nice, udah tepisah per kategori, ty ty
