### ISSUE TITLE
🐞bug saat menambah soal untuk paket latihan soal yang sudah ada

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#34]
karena paket2 latihan soalnya sudah banyak sekarang, paket2 latihan soal yang lebih baru tidak muncul di list drop down untuk latihan soal yang udah ada:

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/8e0a9718-62f4-4e43-8112-2dc1822a5cc0)

harusnya ada lebih banyak lagi daripada yg ada di gambar

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/9325b6d7-28cb-4abd-8778-a4f904cf1696)

**Comment by Uskrai** [comment]
Duplicate of #33

**Comment by AngelaCathe** [comment]
@Uskrai rusdi minta pisah issue tadi, yg ini buat issue yg gk muncul, satunya untuk misahin paket2nya jadi per kategori

**Comment by AngelaCathe** [comment]
**ISSUE DIBATALKAN ----> human error**

ternyata karena paket lat soalnya tipe "kecermatan", sedangkan bank soalnya tipe "pilihan", makanya dia gak muncul.
