### ISSUE TITLE
🪲[NEW BUG] saat membuat paket latihan soal

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#35]
ketika admin/guru membuat paket soal baru, dengan tipe soal "pilihan":

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/331dac79-678e-4b59-b71c-ad16e0b4d2d9)

kemudian mengklik **SUBMIT**, dan diarahkan ke detail paket belajar, tipe soalnya malah keinput jadi "kecermatan":

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/b5d3262c-d497-4586-88aa-8fa7c60ebb94)

**Comment by Uskrai** [comment]
udah
