### ISSUE TITLE
bug: leaderboard lat soal gak sinkron sama record terbaru

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#36]
di kategori bahasa inggris, untuk student5, nilai yang tertinggi di record no.1 :

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/89c6eccd-de3c-4d84-ae91-c1a370ce6936)

tapi di leaderboard, yang terekam malah record no. 6(older record):

![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/b98984fb-53c2-4420-af87-c37015261ba3)

**Comment by Uskrai** [comment]
udah
