### ISSUE TITLE
Dashboard Admin/guru tidak singkron dengan jumlah pengguna di db

### ISSUE THREAD

**Issue by Cibobhap** [ARusDian/ABC-CAT#37]
jumlah pengguna di dashboard berbeda dengan jumlah (semua akun) yang ada di halaman daftar pengguna

dashboar 15 akun:
![Image](https://github.com/ARusDian/ABC-CAT/assets/104015817/3248586a-3508-406f-99db-e882e3d56681)

Vs
daftar pengguna 10 akun:
![Image](https://github.com/ARusDian/ABC-CAT/assets/104015817/d7f05773-dedc-4f1a-a526-111693ac7a4d)

**Comment by Cibobhap** [comment]
sepertinya trouble di halaman pengguna. soalnya setelah aku import student baru, yang nambah ada di dashboard, sedangkan yang di halaman pengguna tidack muncul tetep 10 saja

**Comment by Uskrai** [comment]
Ss jgn di crop biar gampang ceknya

**Comment by Uskrai** [comment]
@ARusDian paginatenya benerin

**Comment by Uskrai** [comment]
udah
