### ISSUE TITLE
Increase Limit Max File Size Input

### ISSUE THREAD

**Issue by ARusDian** [ARusDian/ABC-CAT#39]
Also Dont Forget to change the view

**Comment by ARusDian** [comment]
ini udh di up kn tur di sana?

**Comment by Uskrai** [comment]
Yang mana?
Limit php udh
Ane blom ada kesana

**Comment by Uskrai** [comment]
Gk ada limit text disini din
Sekalian aja tulis yang banyak biar enak ijawabnya

**Comment by ARusDian** [comment]
limit yang di textnya udh juga

**Comment by ARusDian** [comment]
done yak ini
