### ISSUE TITLE
Fix an error that occured while exporting student's test results

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#4]
when admin tries to export "hasil ujian" from one of the students, an error occured(exercise->name) @ARusDian

**Comment by ARusDian** [comment]
Judulnya jelasin njir jangan an error doang ;v

**Comment by AngelaCathe** [comment]
@ARusDian di deskripsinya ada lol, kepanjangan klo ditaroh di judul
atau mau penjelasannya di taroh di judul juga??

**Comment by AngelaCathe** [comment]
@ARusDian eh aku jelasinnya di comment deng 💀 my bad my bad

edit: EH BENER AJA DENG, aku ketiknya di deskripsi errornya tadi tu, dibaca rusdin 🔨

**Comment by ARusDian** [comment]
ini kalo di user (test,student) lain bisa loh btw

keknya ini error di datanya memang deh

soalnya ak coba dilokalku jg bisa

jadi yang error cuma yang IDnya 3

**Comment by AngelaCathe** [comment]
> jadi yang error cuma yang IDnya 3 - @ARusDian 

berarti selama IDnya bukan 3, aman aja? atau gara2 student yg id 3 kemaren sudah ada ngerjain latihan soal ya?

udah nemu kah kenapa dia ngebug di ID 3 rus? atau  mungkin km ada akalin biar ID 3 gak muncul?

**Comment by ARusDian** [comment]
Akalin gmn :v

Ak ndd akses DB sih tpi ya keknya gitu 
Ntar juga diwipe ilang semua jg

**Comment by AngelaCathe** [comment]
ini juga kututup aja ya issuenya @ARusDian sejauh ini kutest udah aman untuk student2nya
