### ISSUE TITLE
background watermark ABC dibuat lebih transparan

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#6]
![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/2f0be56e-14c0-4b04-b414-b7ce8331cdf8)

request klien : tolong buat watermark logo ABC pada background latihan soal menjadi lebih transparan lagi agar warnanya tidak bertabrakan dengan tulisan soalnya

**Comment by ARusDian** [comment]
![Image](https://github.com/ARusDian/ABC-CAT/assets/87649208/a9655f75-4a30-4a08-9872-2f13c604356c)

done (opacity 0.1 from 0.4)
may you check if it's good @AngelaCathe

**Comment by AngelaCathe** [comment]
> may you check if it's good - @ARusDian 

try to open that one question that has long paragraphs in it, see if you can read it just fine with that opacity

**Comment by ARusDian** [comment]
![Image](https://github.com/ARusDian/ABC-CAT/assets/87649208/d734b2dc-5c41-431f-9490-048732ffe065)



![Image](https://github.com/ARusDian/ABC-CAT/assets/87649208/4854164d-fe95-4b1d-b562-2c2ab1dd3f7f)

here check it, what do you think?
