### ISSUE TITLE
Buat grafik untuk hasil ujian soal kecermatan

### ISSUE THREAD

**Issue by AngelaCathe** [ARusDian/ABC-CAT#8]
![Image](https://github.com/ARusDian/ABC-CAT/assets/89586753/c87bfacd-c16d-4a6c-a202-91cc3d1bf152)

Setelah mengerjakan soal kecermatan, hasil ujian akan menampilkan grafik yang dibuat berdasarkan soal yang benar pada tiap kolom. Grafik juga akan muncul di dalam PDF yang dapat didownload dari hasil ujian kecermatan. 

Grafik dibuat seperti gambar di atas

**Comment by ARusDian** [comment]
Udah ada ya tinggal diganti valuenya @Uskrai  🫡

**Comment by Uskrai** [comment]
ini udah kan?

**Comment by AngelaCathe** [comment]
o iya udah, sek kututup issuenya
